sudo: false
# dist: trusty

language: python

cache:
  directories:
    - $HOME/mc

python:
  - 2.7

branches:
  only:
    - master


before_install:
  - if [ -d /home/travis/mc ] ; then export USE_CACHE=yes; echo "Use cache"; else export USE_CACHE=no; fi
  - ./travis/before_install.sh
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - ./travis/install.sh

script:
  - ./travis/run-tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
