name: CI

env: {}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - name: install glut
        run: sudo apt-get update && sudo apt-get install -y freeglut3-dev libglu1-mesa

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ~/.mantid
        run: git clone https://github.com/yxqd/dotmantid ~/.mantid

      # setup conda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: mcvine/label/unstable,mcvine,conda-forge
      
      # use mamba solver
      - name: use mamba solver in conda
        shell: pwsh
        run: |
          # conda update -n base conda
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba

      # install deps and build
      - name: install / build / test
        shell: pwsh
        run: |
          conda install mcvine=1.4 pytest
          mcvine
          py.test -s
